
GET http://localhost:3456/
###
POST http://localhost:3456/create
Content-Type: application/json

{
    "isim": "Anıl Şenocak",
    "email": "anil@senocak.com"
}
###
PUT http://localhost:3456/update/2
Content-Type: application/json

{
    "isim": "Anıl Şenocak2",
    "email": "anil@senocak.com2"
}
###
DELETE http://localhost:3456/delete/2